### PR TITLE
Updating Clean to v1.1.1

### PR DESCRIPTION
**Pull request by talia-storymaker**
Needed to update Clean so that the download link actually leads to a zip file that can be uploaded and installed to ElkArte, rather than the source code (since the latter made it so that there was an extra interior folder, preventing it from working unless you did some tweaking of the folder structure after the fact).

### CODE REVIEW

**Comment by emanuele45** [comment]
Sorry for the late merge. :)

**Comment by talia-storymaker** [comment]
@emanuele45 Thank you. I notice that the ElkArte themes site doesn't seem to be updated to reflect this change. https://themes.elkarte.net/minimal/Clean.html Do you know why?

**Comment by emanuele45** [comment]
@talia-storymaker hmm.. good question, TBH I don't know.
That's @Spuds field of expertise :laughing:

**Comment by Spuds** [comment]
Fixed that for you ... the date needs to be YYYY-MM-DD format it seems.

**Pull request merged**
